"""
Turn the reviewed data into a runnable, re-runnable import.

    python migration/analyze.py && python migration/build_import.py

Writes migration/out/import.sql. Apply it by copying it in as the next Supabase
migration, after the two schema migrations:

    cp migration/out/import.sql supabase/migrations/0003_import_data.sql
    supabase db push

When the rebbeim finish their sheet, regenerate and drop the new file in as
0004_... -- the SQL is idempotent, so re-applying it only moves what changed.

The script is idempotent -- running it twice leaves the database in the same
state as running it once. That matters because the rebbeim are still filling in
their connection sheet; when they send the finished version, re-run analyze.py
and this, and only the new answers change.

What it will NOT do is clobber edits made inside the app. People and staff are
upserted on their natural keys, so a phone number corrected in the app survives
unless the spreadsheet has a different non-empty value for that same field.
"""

import json
import re
from pathlib import Path

OUT = Path(__file__).parent / "out"


def split_display_name(full):
    """
    'Joshua (Shua) Keslassy' -> ('Joshua', 'Keslassy', 'Shua')

    The source list holds one 'Name' column, sometimes with a nickname in
    parentheses and occasionally with a stray trailing comma.
    """
    full = full.strip().strip(",")
    paren = re.search(r"\(([^)]*)\)", full)
    nickname = paren.group(1).strip() if paren else None
    full = re.sub(r"\([^)]*\)", " ", full)
    parts = [p.strip(",") for p in full.split() if p.strip(",")]
    if not parts:
        return full, full, nickname
    if len(parts) == 1:
        return parts[0], parts[0], nickname
    return parts[0], " ".join(parts[1:]), nickname


def lit(v):
    """A SQL literal. None and empty string both become NULL."""
    if v is None or v == "" or v == []:
        return "NULL"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, int):
        return str(v)
    return "'" + str(v).replace("'", "''") + "'"


def rows(values, width=None):
    """
    Render VALUES rows, checking each is as wide as the column list promises.

    A row one field short otherwise surfaces as a Postgres error thousands of
    lines into a 400KB file, which is a miserable thing to track down.
    """
    values = list(values)
    if not values:
        raise ValueError("no rows to insert")
    width = width or len(values[0])
    bad = [i for i, r in enumerate(values) if len(r) != width]
    if bad:
        raise ValueError(
            f"{len(bad)} row(s) are not {width} fields wide; first at index {bad[0]}")
    return ",\n  ".join("(" + ", ".join(r) + ")" for r in values)


def main():
    people = json.loads((OUT / "people.json").read_text())
    enrollments = json.loads((OUT / "enrollments.json").read_text())
    connections = json.loads((OUT / "connections.json").read_text())
    interactions = json.loads((OUT / "interactions.json").read_text())
    staff = json.loads((OUT / "staff.json").read_text())["staff"]

    sql = ["""-- Aish Gesher alumni import. Generated by migration/build_import.py -- do not
-- hand-edit; change the source data or the generator and regenerate.
--
-- Safe to run more than once.
--
-- No explicit BEGIN/COMMIT: this is applied as a Supabase migration, and that
-- runner already wraps each file in a transaction -- a nested COMMIT here would
-- close it early. Running it by hand instead? Use `psql -1 -f` for the same
-- all-or-nothing behaviour.
"""]

    # --- staff ---------------------------------------------------------------
    sql.append(f"""
-- {len(staff)} rabbis. 30 have a tab in the connection workbook; the rest were
-- referenced only by the alumni database's free-text 'Rebbe Contact' column.
insert into staff (name, title, surname) values
  {rows([[lit(s["name"]), lit(s.get("title")), lit(s["surname"])] for s in staff], 3)}
on conflict (name) do update
  set title = excluded.title, surname = excluded.surname;
""")

    # --- people --------------------------------------------------------------
    cols = ["id", "first_name", "last_name", "nickname", "email", "phone",
            "street_address", "city", "state", "zip_code", "country", "hometown",
            "high_school", "college", "grad_school", "occupation",
            "spouse_name", "expected_graduation_year", "do_not_contact",
            "do_not_contact_reason", "learning_post_gesher", "aish_impact",
            "spotlight", "notes", "contact_updated_on"]

    def person_row(p):
        first, last, nickname = split_display_name(p["name"])
        v = dict(
            id=p["alumni_id"], first_name=first, last_name=last,
            nickname=nickname,
            email=p.get("email"), phone=p.get("phone"),
            street_address=p.get("street_address"), city=p.get("city"),
            state=p.get("state"), zip_code=p.get("zip_code"),
            country=p.get("country"),
            # Left NULL: the sheets have one city column, and for alumni years it is a
            # current address while for the intake years it is where he is from.
            hometown=None,
            high_school=p.get("high_school"), college=p.get("college"),
            grad_school=p.get("grad_school"), occupation=p.get("occupation"),
            spouse_name=p.get("spouse_name"),
            expected_graduation_year=p.get("expected_graduation_year"),
            do_not_contact=bool(p.get("do_not_contact")),
            do_not_contact_reason=p.get("do_not_contact_reason"),
            learning_post_gesher=p.get("learning_post_gesher"),
            aish_impact=p.get("aish_impact"),
            spotlight=bool(p.get("spotlight")), notes=p.get("notes"),
            contact_updated_on=p.get("contact_updated_on"),
        )
        return [lit(v[c]) for c in cols]

    # coalesce, not overwrite: a value entered in the app is not thrown away
    # just because this column is blank in the spreadsheet.
    updates = ",\n      ".join(
        f"{c} = coalesce(excluded.{c}, people.{c})" for c in cols
        if c not in ("id", "do_not_contact", "spotlight"))

    sql.append(f"""
-- {len(people)} people, one row each regardless of how many years they were here.
-- Ids are the AlumniIDs the rebbeim's sheet is keyed to -- never regenerate them.
insert into people ({", ".join(cols)}) values
  {rows([person_row(p) for p in people], len(cols))}
on conflict (id) do update
  set {updates},
      do_not_contact = people.do_not_contact or excluded.do_not_contact,
      spotlight = people.spotlight or excluded.spotlight;

-- New people added in the app must not collide with the imported ids.
select setval('people_id_seq', (select max(id) from people));
""")

    # --- aliases -------------------------------------------------------------
    alias_rows = [[lit(p["alumni_id"]), lit(a)]
                  for p in people for a in p.get("aliases", [])]
    sql.append(f"""
-- Spellings folded in during the dedupe review, kept so search still finds a
-- man under the name whoever typed it knew him by.
insert into person_aliases (person_id, alias) values
  {rows(alias_rows, 2)}
on conflict do nothing;
""")

    # --- enrollments ---------------------------------------------------------
    def enrollment_row(e):
        rebbe = (f"(select id from staff where name = {lit(e['rebbe'])})"
                 if e.get("rebbe") else "NULL")
        level = lit(e["program_level"]) + "::program_level" if e["program_level"] else "NULL"
        return [lit(e["person_id"]), lit(e["academic_year"]), level, rebbe]

    sql.append(f"""
-- {len(enrollments)} enrollments. The unique constraint on
-- (person_id, academic_year, level) is what makes the source sheets' duplicated
-- year entries impossible to reproduce.
insert into enrollments (person_id, academic_year, level, rebbe_id) values
  {rows([enrollment_row(e) for e in enrollments], 4)}
on conflict (person_id, academic_year, level) do update
  set rebbe_id = coalesce(excluded.rebbe_id, enrollments.rebbe_id);
""")

    # --- family contacts -----------------------------------------------------
    fam = [[lit(p["alumni_id"]), lit(c["relation"]) + "::family_relation",
            lit(c.get("name")), lit(c.get("email")), lit(c.get("phone"))]
           for p in people for c in p.get("family_contacts", [])
           if c.get("name") or c.get("email") or c.get("phone")]
    ids = ", ".join(str(p["alumni_id"]) for p in people if p.get("family_contacts"))
    sql.append(f"""
-- Parent contacts, from the 2024-25 and 2025-26 intake sheets. There is no
-- natural key here, so imported rows are replaced wholesale rather than
-- accumulating duplicates on a re-run.
delete from family_contacts where person_id in ({ids});
insert into family_contacts (person_id, relation, name, email, phone) values
  {rows(fam, 5)};
""")

    # --- staff connections ---------------------------------------------------
    conn_rows = [[f"(select id from staff where name = {lit(c['staff'])})",
                  lit(c["person_id"])] for c in connections]
    sql.append(f"""
-- {len(connections)} 'want to stay in touch with' answers, replacing 30
-- near-identical spreadsheet tabs. Re-running picks up whatever the rabbis have
-- added since without disturbing what is already here.
insert into staff_connections (staff_id, person_id) values
  {rows(conn_rows, 2)}
on conflict do nothing;
""")

    # --- interactions --------------------------------------------------------
    campaigns = sorted({i["campaign"] for i in interactions})
    inter_rows = [[lit(i["person_id"]), "'2022-01-01'::date", lit(i["campaign"]),
                   (f"(select id from staff where name = {lit(i['staff'])})"
                    if i.get("staff") else "NULL")]
                  for i in interactions]
    sql.append(f"""
-- Campaign touchpoints from the 'Rebbe Contact - Alumni 2022' tab. That sheet
-- records only whether an alumnus was reached in a given push, not when, so the
-- date is a placeholder and the campaign name carries the real meaning.
delete from interactions where campaign in ({", ".join(lit(c) for c in campaigns)});
insert into interactions (person_id, occurred_on, campaign, staff_id) values
  {rows(inter_rows, 4)};
""")

    path = OUT / "import.sql"
    text = "\n".join(sql)
    path.write_text(text, encoding="utf-8")
    print(f"wrote {path}  ({len(text)//1024} KB)")
    print(f"  staff {len(staff)} | people {len(people)} | aliases {len(alias_rows)}")
    print(f"  enrollments {len(enrollments)} | family contacts {len(fam)}")
    print(f"  connections {len(connections)} | interactions {len(inter_rows)}")


if __name__ == "__main__":
    main()
