const { withAppBuildGradle } = require('expo/config-plugins');

/**
 * Ship native code for one CPU architecture instead of four.
 *
 * Expo's prebuild targets armeabi-v7a, arm64-v8a, x86 and x86_64, and each gets
 * a complete copy of Hermes and the React Native binaries -- 45MB of an APK, of
 * which only arm64 can ever run on a phone. x86 and x86_64 exist for emulators;
 * armeabi-v7a is 32-bit devices, roughly pre-2017.
 *
 * The gradle property `reactNativeArchitectures` is not enough on its own: it
 * constrains React Native's own libraries, but prebuilt AARs -- Fresco, the
 * Expo modules -- ship every ABI regardless and get merged in. abiFilters is
 * applied at packaging, so it catches those too.
 *
 * A config plugin rather than a hand edit because android/ is regenerated by
 * every prebuild, and a hand edit would silently vanish.
 */
module.exports = function withAbiFilters(config, { abis = ['arm64-v8a'] } = {}) {
  return withAppBuildGradle(config, (cfg) => {
    if (cfg.modResults.language !== 'groovy') {
      throw new Error('withAbiFilters expects a groovy build.gradle');
    }
    if (cfg.modResults.contents.includes('abiFilters')) {
      return cfg;
    }

    const list = abis.map((a) => `"${a}"`).join(', ');
    const block = [
      '',
      '        // Injected by plugins/withAbiFilters.js -- see the note there for why',
      '        // reactNativeArchitectures alone does not do this.',
      '        ndk {',
      `            abiFilters ${list}`,
      '        }',
    ].join('\n');

    // Anchored on the versionName line rather than on `defaultConfig {`, because
    // the string "defaultConfig" also appears in comments in the template.
    const anchor = /(defaultConfig\s*\{[\s\S]*?versionName\s+"[^"]*")/;
    if (!anchor.test(cfg.modResults.contents)) {
      throw new Error('withAbiFilters could not find defaultConfig/versionName');
    }
    cfg.modResults.contents = cfg.modResults.contents.replace(anchor, `$1${block}`);
    return cfg;
  });
};
